# Generated by Django 6.0.4 on 2026-04-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheet',
            options={'ordering': ['-id'], 'verbose_name': 'Sheet', 'verbose_name_plural': 'Sheets'},
        ),
    ]
